### PR TITLE
Move Form and Decorate Home Page, Add User Context to Countries and Form

### PR DESCRIPTION
**Pull request by gobrien06**
## Overview
Adds UserContext that holds username and videos for all countries and home page.
Adds text + entry button to home page with animations.
Moves PubForm from 'Experimental Metrics' to Home page.
Adds additional error reporting to top of country pages.

## Materials
- #36 (does not complete)

## Pictures
homeaddingdata
image
image

## Manual Testing Guide
- Navigate to the home page
- Click the enter data button
- Enter a date without a name and notice that the data was saved
- Navigate to KR, and notice under 'Experimental Metrics' the data is shown
- 

Pull requests should receive approval before merge.

### CODE REVIEW

**Comment by gobrien06** [comment]
Added backend connection.

Now when you save to a username that exist, their results show up in a list under the form as well as on other country pages.
Additionally adds the loaders back to the 'General Information' section.

Some data exists in the json already to toy with.

image

**Comment by JakinChan200** [comment]
How long is the error message on the top of the page supposed to last? 
At the moment, "Error fetching video data." lasts until you switch to a different country

**Comment by gobrien06** [comment]
> How long is the error message on the top of the page supposed to last? At the moment, "Error fetching video data." lasts until you switch to a different country

Yeah, for now it lasts until you switch countries. If you have the server running however there shouldn't be any errors

**Comment by JakinChan200** [comment]
The error pops up when there are no videos in a specific category (eg KR Drama)

I don't know if this is a result of this pull request or from a different one, but when there are no videos in a specific category, the category list shows the videos from the last search

**Comment by gobrien06** [comment]
> The error pops up when there are no videos in a specific category (eg KR Drama)
> 
> I don't know if this is a result of this pull request or from a different one, but when there are no videos in a specific category, the category list shows the videos from the last search

Oh I forgot to test that, I'll remove the errors from categories and reset them when a successful request lands for general results.

As for the previous category sticking, I haven't had that happen before so I'll investigate this PR to see if I can resolve that today/tomorrow.

**Comment by gobrien06** [comment]
> The error pops up when there are no videos in a specific category (eg KR Drama)
> 
> I don't know if this is a result of this pull request or from a different one, but when there are no videos in a specific category, the category list shows the videos from the last search

Updated

**Review by JakinChan200 — APPROVED** [review]
LGTM - Looks like it works as intended

**Pull request merged**
